dist: trusty
cache:
  - bundler
addons:
  postgresql: "9.6"
language: ruby
rvm:
 - 2.5.1
gemfile:
  - gemfiles/rails_6.0.0.gemfile
  - gemfiles/rails_6.1.0.gemfile
  - gemfiles/rails_7.0.0.gemfile
  - gemfiles/rails_7.0.4.gemfile
before_script:
  - cp spec/dummy/config/database.yml{.sample,}
  - bundle exec rake db:create db:schema:load db:test:prepare --Rakefile spec/dummy/Rakefile
script: bundle exec rspec spec
